### ISSUE TITLE
Icon missing and service outage :(

### ISSUE THREAD

**Issue by zeg-io** [VincentLoy/brackets-ui-faces-and-names#1]
I like the add-on but there are a couple issues:
1. The icon doesn't show up.  I tried replacing it with an SVG by bumming some code from another add-on but that didn't work either.  The button is present, but there is nothing on it.
2. Several times now the uifaces.com site has been down, but when you click on "Generate UI Face" there is no alert...it just sits there like the add-on is broken.  I'd suggest having it poll the site when it first loads to warn of an outage, or at least have it return "getting error from uifaces.com" or the like

**Comment by VincentLoy** [comment]
Hi @zeg-io ! Thanks for the feedback.

The icon show up well on my computer, I'm running a Linux Debian 8 with the last version of Brackets (1.6). Can you tell me more about your settings ?

Here I have two icons (dev version and current downloadable one)
![capture du 2016-02-01 19 51 02](https://cloud.githubusercontent.com/assets/7996741/12727408/3aee7566-c91d-11e5-9e98-d9bebe00fb53.png)

For the second point, I'm checking out :)

**Comment by VincentLoy** [comment]
I updated the plugin here https://github.com/VincentLoy/brackets-ui-faces-and-names/releases/tag/v1.1.0 

You can update it as well directly into the Brackets Extension manager.

You can now choose a country to generate a name and if UI Faces or UI Names API request fails, it'll bump an alert message with the status code, etc.

Thanks for the feedback :)

**Comment by zeg-io** [comment]
Yes indeed the icon now shows!  :)  Thank you!

**Comment by VincentLoy** [comment]
Happy to hear it ! :)
