### ISSUE TITLE
http://uifaces.com/authorized

### ISSUE THREAD

**Issue by Randore** [VincentLoy/brackets-ui-faces-and-names#2]
Not working
![screen shot 2016-05-10 at 12 12 20 pm](https://cloud.githubusercontent.com/assets/443526/15137662/d0ffa4de-16a8-11e6-8679-50bb7b4eed8d.png)

**Comment by VincentLoy** [comment]
Hi @Randore, It's actually working well for me.Probably uifaces.com had some server issue this day. 
Did you tried again ?

![capture](https://cloud.githubusercontent.com/assets/7996741/15197259/b03a7caa-17d0-11e6-80cc-116ef561c55c.PNG)
